### PR TITLE
feat(portal): add push activity log

### PR DESCRIPTION
**Pull request by KsiBart**
## Description
As a control plane admin user, I can push selected API activity log to other system through a registered callback for debugging purpose

a/c:

- [x] admin can push api activity logs by selecting a time range and env(stage or production) only if callback is registered
- [x] max time range is 7 days
- [ ] Push history is available
 -- who
-- when
 -- env
-- time range
-- status - in progress, done, failed
- [ ] this feature should be able to be hided through a feature flag

## Related Issue
#122 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring or add test (improvements in base code or adds test coverage to functionality)
- [ ] CI/CD or documentation update (changes to CI/CD pipeline or documentation)

## Checklist

- [x] I ensured that the documentation is up to date
- [x] I explained why this PR updates in detail with reasoning why it's required
- [x] I would like a code coverage CI quality gate exception and have explained why

### CODE REVIEW

**Review by james-tran-3005 — APPROVED** [review]
LGTM

**Review by james-tran-3005 — DISMISSED** [review]
LGTM

**Review by zhiyaoPCCW — CHANGES_REQUESTED** [review]
code smells need to be fixed first.

**Review by james-tran-3005 — APPROVED** [review]
LGTM

**Review by zhiyaoPCCW — APPROVED** [review]
LGTM

**Pull request merged**
